# Generated by Django 5.0.1 on 2024-01-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyitem",
            name="other_items",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="surveyitem",
            name="assessment_date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="surveyitem",
            name="premisis_occupaid_vacant",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="surveyitem",
            name="survey_items",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
