# Generated by Django 5.0.1 on 2024-01-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_surveyitem_other_items_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveyitem",
            name="other_items",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
